=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/src/testdata/mathexpression/t1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/t1/" targetNamespace="http://www.example.org/t1/">
    <complexType name="T1">
    	<sequence>
    		<element name="a1" type="decimal" maxOccurs="1" minOccurs="1"></element>
    		<element name="b1" type="decimal" maxOccurs="1" minOccurs="1"></element>
    		<element name="c1" type="decimal" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <element name="t1" type="tns:T1"></element>
    
    <element name="collection" type="tns:CollectionType"></element>
    
    <complexType name="CollectionType">
    	<sequence>
    		<element ref="tns:t1" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/src/testdata/formatstring/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:collection xmlns:tns="http://www.example.org/t1/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/t1/ t1.xsd">
    <tns:t1 id="id0">
        <a1>Hello</a1>
        <b1>Hale</b1>
        <c1>World</c1>
    </tns:t1>
    <tns:t1 id="id1">
        <a1>World</a1>
        <b1>Hello</b1>
        <c1>Hale</c1>
    </tns:t1>
</tns:collection>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/simplemerge/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:collection xmlns:tns="http://www.example.org/t1/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/t1/ t1.xsd">
    <tns:t1>
        <a1>a</a1>
        <b1>b</b1>
        <c1>c_1</c1>
        <c1>c_2</c1>
        <c1>c_3</c1>
        <c1>c_4</c1>
        <c1>c_5</c1>
    </tns:t1>
</tns:collection>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/nullvalue/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:collection xmlns:tns="http://www.example.org/t1/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/t1/ t1.xsd">
    <tns:t1 id="id0">
        <a1>1</a1>
        <b1>b10</b1>
        <c1>6</c1>
    </tns:t1>
    <tns:t1 id="id1">
        <a1>5</a1>
        <b1>b10</b1>
        <c1>4</c1>
    </tns:t1>
</tns:collection>
