=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/join_multi_cond_1/t2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/t2/" targetNamespace="http://www.example.org/t2/">
    <complexType name="GemeindeType">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="flaeche" type="double"></element>
    		<element name="teile" type="int"></element>
    		<element name="schluessel" maxOccurs="1" minOccurs="1">
    			<complexType>
    				<sequence>
    					<element name="land" type="string"></element>
    					<element name="bezirk" type="string"></element>
    					<element name="gemeinde" type="string"></element>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="id" type="int"></attribute>
    </complexType>
    
    <element name="gemeinde" type="tns:GemeindeType"></element>
    
    <element name="collection" type="tns:CollectionType"></element>
    
    <complexType name="CollectionType">
    	<sequence>
    		<element ref="tns:gemeinde" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/join_multi_cond_1/instance2.xml
<?xml version="1.0" ?>
<tns:collection xmlns:ns1="http://www.w3.org/1999/xhtml" xmlns:tns="http://www.example.org/t2/" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/t2/ file:/home/simon/repos/hale/cst/plugins/eu.esdihumboldt.cst.test/src/testdata/join_multi_cond_1/t2.xsd">
  <tns:gemeinde id="1">
    <name>HÃ¼ttenberg</name>
    <flaeche>15.0</flaeche>
    <teile>3</teile>
    <schluessel>
      <land>0X</land>
      <bezirk>2</bezirk>
      <gemeinde>6000</gemeinde>
    </schluessel>
  </tns:gemeinde>
  <tns:gemeinde id="2">
    <name>Darmstadt</name>
    <flaeche>23.0</flaeche>
    <teile>1</teile>
    <schluessel>
      <land>0X</land>
      <bezirk>2</bezirk>
      <gemeinde>4000</gemeinde>
    </schluessel>
  </tns:gemeinde>
</tns:collection>
