=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/group/t2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/t2/" targetNamespace="http://www.example.org/t2/">
    <complexType name="PersonType">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="details" maxOccurs="1" minOccurs="0">
    			<complexType>
    				<sequence>
    					<element name="age" type="string" maxOccurs="1" minOccurs="0"></element>
    					<element name="income" type="string" maxOccurs="1" minOccurs="0"></element>
    					<sequence minOccurs="0" maxOccurs="unbounded">
				    		<element name="street" type="string"></element>
				    		<element name="city" type="string"></element>
				    	</sequence>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <element name="person" type="tns:PersonType"></element>

	<element name="collection" type="tns:CollectionType"></element>
    
    <complexType name="CollectionType">
    	<sequence>
    		<element ref="tns:person" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/simplecomplex/instance2_result.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:collection xmlns:tns="http://www.example.org/t2/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/t2/ t2.xsd">
    <tns:person id="id0">
        <name>name0</name>
        <details>
            <age>income0</age>
            <income>age0</income>
            <address>
                <street>city0</street>
                <city>street0</city>
            </address>
            <address>
                <street>city1</street>
                <city>street1</city>
            </address>
        </details>
    </tns:person>
    <tns:person id="id1">
        <name>name1</name>
        <details>
            <age>income1</age>
            <income>age1</income>
            <address>
                <street>city2</street>
                <city>street2</city>
            </address>
            <address>
                <street>city3</street>
                <city>street3</city>
            </address>
        </details>
    </tns:person>
</tns:collection>
