=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/cm_nested_5/t2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/t2/" targetNamespace="http://www.example.org/t2/">
    <complexType name="T2">
    	<sequence>
    		<element name="element" maxOccurs="unbounded" minOccurs="0">
				<complexType>
					<sequence>
						<element name="b" maxOccurs="unbounded" minOccurs="0">
							<complexType>
								<sequence>
									<element name="b1" type="string" maxOccurs="unbounded"
										minOccurs="0"></element>
									<element name="b2" type="string" maxOccurs="unbounded"
										minOccurs="0"></element>
								</sequence>
							</complexType>
						</element>
						<element name="d" maxOccurs="unbounded" minOccurs="0">
							<complexType>
								<sequence>
									<element name="d1" type="string" maxOccurs="unbounded"
										minOccurs="0"></element>
									<element name="d2" type="string" maxOccurs="unbounded"
										minOccurs="0"></element>
								</sequence>
							</complexType>
						</element>
					</sequence>
				</complexType>
			</element>
    	</sequence>
    </complexType>

    <element name="t2" type="tns:T2"></element>

    <element name="collection" type="tns:CollectionType"></element>
    
    <complexType name="CollectionType">
    	<sequence>
    		<element ref="tns:t2" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/src/testdata/cm_union_1/instance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:collection xmlns:tns="http://www.example.org/t2/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/t2/ t2.xsd">
    <tns:t2>
        <b>a10</b>
        <b>a11</b>
        <b>a12</b>
        <b>a20</b>
        <b>a21</b>
        <b>a22</b>
    </tns:t2>
    <tns:t2>
        <b>a13</b>
        <b>a14</b>
        <b>a15</b>
        <b>a23</b>
        <b>a24</b>
        <b>a25</b>
    </tns:t2>
    <tns:t2>
        <b>a16</b>
        <b>a17</b>
        <b>a18</b>
        <b>a26</b>
        <b>a27</b>
        <b>a28</b>
    </tns:t2>
</tns:collection>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/cm_nested_1/instance2.xml
<?xml version="1.0" ?>
<tns:collection xmlns:tns="http://www.example.org/t2/" xmlns:ns1="http://www.w3.org/1999/xhtml" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/t2/ file:/home/simon-local/repos/hale/cst/plugins/eu.esdihumboldt.cst.test/src/testdata/cm_nested_1/t2.xsd">
  <tns:t2>
    <b>
      <b1>a10</b1>
      <b1>a11</b1>
      <b1>a12</b1>
      <b1>a13</b1>
      <b1>a14</b1>
      <b2>a20</b2>
      <b2>a21</b2>
      <b2>a22</b2>
      <b2>a23</b2>
      <b2>a24</b2>
    </b>
    <b>
      <b1>a15</b1>
      <b1>a16</b1>
      <b1>a17</b1>
      <b1>a18</b1>
      <b1>a19</b1>
      <b2>a25</b2>
      <b2>a26</b2>
      <b2>a27</b2>
      <b2>a28</b2>
      <b2>a29</b2>
    </b>
    <b>
      <b1>a110</b1>
      <b1>a111</b1>
      <b1>a112</b1>
      <b1>a113</b1>
      <b1>a114</b1>
      <b2>a210</b2>
      <b2>a211</b2>
      <b2>a212</b2>
      <b2>a213</b2>
      <b2>a214</b2>
    </b>
    <b>
      <b1>a115</b1>
      <b1>a116</b1>
      <b1>a117</b1>
      <b1>a118</b1>
      <b1>a119</b1>
      <b2>a215</b2>
      <b2>a216</b2>
      <b2>a217</b2>
      <b2>a218</b2>
      <b2>a219</b2>
    </b>
    <b>
      <b1>a120</b1>
      <b1>a121</b1>
      <b1>a122</b1>
      <b1>a123</b1>
      <b1>a124</b1>
      <b2>a220</b2>
      <b2>a221</b2>
      <b2>a222</b2>
      <b2>a223</b2>
      <b2>a224</b2>
    </b>
  </tns:t2>
  <tns:t2>
    <b>
      <b1>a125</b1>
      <b1>a126</b1>
      <b1>a127</b1>
      <b1>a128</b1>
      <b1>a129</b1>
      <b2>a225</b2>
      <b2>a226</b2>
      <b2>a227</b2>
      <b2>a228</b2>
      <b2>a229</b2>
    </b>
    <b>
      <b1>a130</b1>
      <b1>a131</b1>
      <b1>a132</b1>
      <b1>a133</b1>
      <b1>a134</b1>
      <b2>a230</b2>
      <b2>a231</b2>
      <b2>a232</b2>
      <b2>a233</b2>
      <b2>a234</b2>
    </b>
    <b>
      <b1>a135</b1>
      <b1>a136</b1>
      <b1>a137</b1>
      <b1>a138</b1>
      <b1>a139</b1>
      <b2>a235</b2>
      <b2>a236</b2>
      <b2>a237</b2>
      <b2>a238</b2>
      <b2>a239</b2>
    </b>
    <b>
      <b1>a140</b1>
      <b1>a141</b1>
      <b1>a142</b1>
      <b1>a143</b1>
      <b1>a144</b1>
      <b2>a240</b2>
      <b2>a241</b2>
      <b2>a242</b2>
      <b2>a243</b2>
      <b2>a244</b2>
    </b>
    <b>
      <b1>a145</b1>
      <b1>a146</b1>
      <b1>a147</b1>
      <b1>a148</b1>
      <b1>a149</b1>
      <b2>a245</b2>
      <b2>a246</b2>
      <b2>a247</b2>
      <b2>a248</b2>
      <b2>a249</b2>
    </b>
  </tns:t2>
  <tns:t2>
    <b>
      <b1>a150</b1>
      <b1>a151</b1>
      <b1>a152</b1>
      <b1>a153</b1>
      <b1>a154</b1>
      <b2>a250</b2>
      <b2>a251</b2>
      <b2>a252</b2>
      <b2>a253</b2>
      <b2>a254</b2>
    </b>
    <b>
      <b1>a155</b1>
      <b1>a156</b1>
      <b1>a157</b1>
      <b1>a158</b1>
      <b1>a159</b1>
      <b2>a255</b2>
      <b2>a256</b2>
      <b2>a257</b2>
      <b2>a258</b2>
      <b2>a259</b2>
    </b>
    <b>
      <b1>a160</b1>
      <b1>a161</b1>
      <b1>a162</b1>
      <b1>a163</b1>
      <b1>a164</b1>
      <b2>a260</b2>
      <b2>a261</b2>
      <b2>a262</b2>
      <b2>a263</b2>
      <b2>a264</b2>
    </b>
    <b>
      <b1>a165</b1>
      <b1>a166</b1>
      <b1>a167</b1>
      <b1>a168</b1>
      <b1>a169</b1>
      <b2>a265</b2>
      <b2>a266</b2>
      <b2>a267</b2>
      <b2>a268</b2>
      <b2>a269</b2>
    </b>
    <b>
      <b1>a170</b1>
      <b1>a171</b1>
      <b1>a172</b1>
      <b1>a173</b1>
      <b1>a174</b1>
      <b2>a270</b2>
      <b2>a271</b2>
      <b2>a272</b2>
      <b2>a273</b2>
      <b2>a274</b2>
    </b>
  </tns:t2>
  <tns:t2>
    <b>
      <b1>a175</b1>
      <b1>a176</b1>
      <b1>a177</b1>
      <b1>a178</b1>
      <b1>a179</b1>
      <b2>a275</b2>
      <b2>a276</b2>
      <b2>a277</b2>
      <b2>a278</b2>
      <b2>a279</b2>
    </b>
    <b>
      <b1>a180</b1>
      <b1>a181</b1>
      <b1>a182</b1>
      <b1>a183</b1>
      <b1>a184</b1>
      <b2>a280</b2>
      <b2>a281</b2>
      <b2>a282</b2>
      <b2>a283</b2>
      <b2>a284</b2>
    </b>
    <b>
      <b1>a185</b1>
      <b1>a186</b1>
      <b1>a187</b1>
      <b1>a188</b1>
      <b1>a189</b1>
      <b2>a285</b2>
      <b2>a286</b2>
      <b2>a287</b2>
      <b2>a288</b2>
      <b2>a289</b2>
    </b>
    <b>
      <b1>a190</b1>
      <b1>a191</b1>
      <b1>a192</b1>
      <b1>a193</b1>
      <b1>a194</b1>
      <b2>a290</b2>
      <b2>a291</b2>
      <b2>a292</b2>
      <b2>a293</b2>
      <b2>a294</b2>
    </b>
    <b>
      <b1>a195</b1>
      <b1>a196</b1>
      <b1>a197</b1>
      <b1>a198</b1>
      <b1>a199</b1>
      <b2>a295</b2>
      <b2>a296</b2>
      <b2>a297</b2>
      <b2>a298</b2>
      <b2>a299</b2>
    </b>
  </tns:t2>
  <tns:t2>
    <b>
      <b1>a1100</b1>
      <b1>a1101</b1>
      <b1>a1102</b1>
      <b1>a1103</b1>
      <b1>a1104</b1>
      <b2>a2100</b2>
      <b2>a2101</b2>
      <b2>a2102</b2>
      <b2>a2103</b2>
      <b2>a2104</b2>
    </b>
    <b>
      <b1>a1105</b1>
      <b1>a1106</b1>
      <b1>a1107</b1>
      <b1>a1108</b1>
      <b1>a1109</b1>
      <b2>a2105</b2>
      <b2>a2106</b2>
      <b2>a2107</b2>
      <b2>a2108</b2>
      <b2>a2109</b2>
    </b>
    <b>
      <b1>a1110</b1>
      <b1>a1111</b1>
      <b1>a1112</b1>
      <b1>a1113</b1>
      <b1>a1114</b1>
      <b2>a2110</b2>
      <b2>a2111</b2>
      <b2>a2112</b2>
      <b2>a2113</b2>
      <b2>a2114</b2>
    </b>
    <b>
      <b1>a1115</b1>
      <b1>a1116</b1>
      <b1>a1117</b1>
      <b1>a1118</b1>
      <b1>a1119</b1>
      <b2>a2115</b2>
      <b2>a2116</b2>
      <b2>a2117</b2>
      <b2>a2118</b2>
      <b2>a2119</b2>
    </b>
    <b>
      <b1>a1120</b1>
      <b1>a1121</b1>
      <b1>a1122</b1>
      <b1>a1123</b1>
      <b1>a1124</b1>
      <b2>a2120</b2>
      <b2>a2121</b2>
      <b2>a2122</b2>
      <b2>a2123</b2>
      <b2>a2124</b2>
    </b>
  </tns:t2>
</tns:collection>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/inline_3/instance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:collection xmlns:tns="http://www.example.org/t2/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/t2/ t2.xsd">
    <tns:t2>
        <item>
            <tns:b>
                <b1>a10</b1>
                <b1>a11</b1>
                <b1>a12</b1>
                <b2>a20</b2>
                <b2>a21</b2>
                <b2>a22</b2>
            </tns:b>
            <tns:b>
                <b1>a13</b1>
                <b1>a14</b1>
                <b1>a15</b1>
                <b2>a23</b2>
                <b2>a24</b2>
                <b2>a25</b2>
            </tns:b>
        </item>
    </tns:t2>
</tns:collection>
