=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/src/testdata/choice/t1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/t1/" targetNamespace="http://www.example.org/t1/">
    <complexType name="T1">
    	<sequence>
    		<element name="personName" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="personAge" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="personIncome" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="personStreet" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="personPOB" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="personCity" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <element name="t1" type="tns:T1"></element>
    
     <element name="collection" type="tns:CollectionType"></element>
    
    <complexType name="CollectionType">
    	<sequence>
    		<element ref="tns:t1" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/choice/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:collection xmlns:tns="http://www.example.org/t1/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/t1/ t1.xsd">
    <tns:t1>
        <personName>personName0</personName>
        <personAge>personAge0</personAge>
        <personIncome>personIncome0</personIncome>
        <personStreet>personStreet0</personStreet>
        <personPOB>personPOB0</personPOB>
        <personCity>personCity0</personCity>
    </tns:t1>
    <tns:t1>
        <personName>personName1</personName>
        <personAge>personAge1</personAge>
        <personIncome>personIncome1</personIncome>
        <personStreet>personStreet1</personStreet>
        <personPOB>personPOB1</personPOB>
        <personCity>personCity1</personCity>
    </tns:t1>
    <tns:t1>
        <personName>personName2</personName>
        <personAge>personAge2</personAge>
        <personIncome>personIncome2</personIncome>
        <personStreet>personStreet2</personStreet>
        <personPOB>personPOB2</personPOB>
        <personCity>personCity2</personCity>
    </tns:t1>
    <tns:t1>
        <personName>personName3</personName>
        <personAge>personAge3</personAge>
        <personIncome>personIncome3</personIncome>
        <personStreet>personStreet3</personStreet>
        <personPOB>personPOB3</personPOB>
        <personCity>personCity3</personCity>
    </tns:t1>
    <tns:t1>
        <personName>personName4</personName>
        <personAge>personAge4</personAge>
        <personIncome>personIncome4</personIncome>
        <personStreet>personStreet4</personStreet>
        <personPOB>personPOB4</personPOB>
        <personCity>personCity4</personCity>
    </tns:t1>
</tns:collection>
