=== halestudio/hale/doc/plugins/eu.esdihumboldt.hale.doc.user/projects/typefilter/t1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/t1/" targetNamespace="http://www.example.org/t1/">
    <complexType name="ItemType">
    	<sequence>
    		<element name="name" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="price" type="float" minOccurs="0" maxOccurs="1"></element>
    		<element name="type" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="shirt" />
    					<enumeration value="hat" />
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <element name="item" type="tns:ItemType"></element>
    
    <element name="collection" type="tns:CollectionType"></element>
    
    <complexType name="CollectionType">
    	<sequence>
    		<element ref="tns:item" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/src/testdata/typefilter/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:collection xmlns:tns="http://www.example.org/t1/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/t1/ t1.xsd">
    <tns:item id="1">
        <name>Polo shirt green</name>
        <price>9.99</price>
        <type>shirt</type>
    </tns:item>
    <tns:item id="2">
        <name>Top hat</name>
        <price>29.99</price>
        <type>hat</type>
    </tns:item>
</tns:collection>
