=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/impassign/t2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/t2/" targetNamespace="http://www.example.org/t2/">
    <complexType name="T2">
    	<sequence>
    		<element name="name" maxOccurs="unbounded" minOccurs="0">
    			<complexType>
    				<sequence>
    					<element name="nilReason" type="string" minOccurs="0"></element>
    					<element name="Name" type="tns:NameType"></element>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <element name="t2" type="tns:T2"></element>

    <complexType name="NameType">
    	<sequence>
    		<element name="language" type="string"></element>
    		<element name="spelling" type="tns:SpellingType"></element>
    	</sequence>
    </complexType>

    <complexType name="SpellingType">
    	<sequence>
    		<element name="text" type="string"></element>
    	</sequence>
    </complexType>
    
    <element name="collection" type="tns:CollectionType"></element>
    
    <complexType name="CollectionType">
    	<sequence>
    		<element ref="tns:t2" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== halestudio/hale/cst/plugins/eu.esdihumboldt.cst.test/testdata/impassign/instance2.xml
<?xml version="1.0" ?>
<tns:collection xmlns:tns="http://www.example.org/t2/" xmlns:ns1="http://www.w3.org/1999/xhtml" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/t2/ file:/home/simon/repos/hale/cst/plugins/eu.esdihumboldt.cst.test/src/testdata/impassign/t2.xsd">
  <tns:t2 id="id1">
    <name>
      <Name>
        <language>de</language>
        <spelling>
          <text>name_de1</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>en</language>
        <spelling>
          <text>name_en1</text>
        </spelling>
      </Name>
    </name>
  </tns:t2>
  <tns:t2 id="id3">
    <name>
      <Name>
        <language>de</language>
        <spelling>
          <text>name_de3</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>en</language>
        <spelling>
          <text>name_en3</text>
        </spelling>
      </Name>
    </name>
  </tns:t2>
  <tns:t2 id="id2">
    <name>
      <Name>
        <language>fr</language>
        <spelling>
          <text>name_fr2</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>en</language>
        <spelling>
          <text>name_en2</text>
        </spelling>
      </Name>
    </name>
  </tns:t2>
  <tns:t2 id="id0">
    <name>
      <Name>
        <language>fr</language>
        <spelling>
          <text>name_fr0</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>de</language>
        <spelling>
          <text>name_de0</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>en</language>
        <spelling>
          <text>name_en0</text>
        </spelling>
      </Name>
    </name>
  </tns:t2>
  <tns:t2 id="id4">
    <name>
      <Name>
        <language>fr</language>
        <spelling>
          <text>name_fr4</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>de</language>
        <spelling>
          <text>name_de4</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>en</language>
        <spelling>
          <text>name_en4</text>
        </spelling>
      </Name>
    </name>
  </tns:t2>
  <tns:t2 id="id6">
    <name>
      <Name>
        <language>fr</language>
        <spelling>
          <text>name_fr6</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>de</language>
        <spelling>
          <text>name_de6</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>en</language>
        <spelling>
          <text>name_en6</text>
        </spelling>
      </Name>
    </name>
  </tns:t2>
  <tns:t2>
    <name>
      <Name>
        <language>de</language>
        <spelling>
          <text>name_de5</text>
        </spelling>
      </Name>
    </name>
    <name>
      <Name>
        <language>en</language>
        <spelling>
          <text>name_en5</text>
        </spelling>
      </Name>
    </name>
  </tns:t2>
</tns:collection>
